version: '3'

services:
  mailpit:
    container_name: mailpit
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - mailpit
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.${DOMAIN}`)"
      - "traefik.http.routers.mail.service=mail"
      - "traefik.http.services.mail.loadbalancer.server.port=8025"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls.certresolver=leresolver"
      - "traefik.http.routers.mail.middlewares=mail-auth"
      - "traefik.http.middlewares.mail-auth.digestauth.users=${DIGESTAUTH_USERS}"

networks:
  mailpit:
    name: mailpit
  gateway:
    external: true
