version: '3'

services:
  mailpit:
    container_name: mailpit
    image: axllent/mailpit:latest
    restart: unless-stopped
    networks:
      - mailpit
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.${DOMAIN}`)"
      - "traefik.http.routers.mail.service=mail"
      - "traefik.http.services.mail.loadbalancer.server.port=8025"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls.certresolver=leresolver"
      - "traefik.http.routers.mail.middlewares=mailpit-auth"
      # https://doc.traefik.io/traefik/middlewares/http/digestauth/
      # htdigest users_credentials traefik admin
      - "traefik.http.middlewares.mailpit-auth.digestauth.usersfile=/users_credentials"
    volumes:
      - "./users_credentials:/users_credentials:ro"

networks:
  mailpit:
  gateway:
    external: true
