# https://docs.gitlab.com/runner/install/docker.html
version: '3'

services:
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - 'gitlab_runner_config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  gitlab_runner_config:
    name: gitlab_runner_config
