version: '3'

services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD-root}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-}'
      MYSQL_USER: '${DB_USERNAME:-}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql

volumes:
  mysql:

networks:
  mysql:
    name: mysql
