version: '3'

services:
  redis:
    container_name: redis
    restart: alwaye
    image: redis:7.0
    volumes:
      - 'redis:/data'
    networks:
      - redis

networks:
  redis:
    name: redis

volumes:
  redis:
