version: '3'

services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0-alpine
    volumes:
      - 'redis:/data'
    networks:
      - redis

networks:
  redis:
    name: redis

volumes:
  redis:
